# Generated by Django 6.1 on 2026-08-13 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_profile_bio_profile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
