# Generated by Django 6.1 on 2026-09-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_profile_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_timeout_seconds', models.PositiveIntegerField(default=300, help_text='Session auto-logout timer in seconds (e.g., 30 = 30 seconds, 300 = 5 minutes).')),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
    ]
